name: "GitLint Action"
description: "Check if naming conventions for commits, branches, and pull requests are respected"
branding:
  icon: "check"
  color: "blue"
inputs:
  commit-message-body-max-length:
    description: "Max. length of commit message body"
    required: false
    default: 72
  commit-message-body-min-length:
    description: "Min. length of commit message body"
    required: false
    default: -1
  commit-message-subject-max-length:
    description: "Max. length of commit message subject"
    required: false
    default: 72
  commit-message-subject-min-length:
    description: "Min. length of commit message subject"
    required: false
    default: -1
  github-token:
    description: "GitHub token used to access api"
    required: true
    default: ${{ github.token }}
  prohibit-blank-lines-cm-body:
    description: "Prohibit blank lines in commit message body"
    required: false
    default: false
  prohibit-unknown-commit-authors:
    description: "Prohibit commit authors that are not known to GitHub"
    required: false
    default: false
  prohibit-unknown-commit-committers:
    description: "Prohibit commit committers that are not known to GitHub"
    required: false
    default: false
  prohibit-unsigned-commits:
    description: "Prohibit commits without a valid signature"
    required: false
    default: false
  re-branch-name:
    description: "Regular expression to check branch name"
    required: false
    default: ".*"
  re-commit-author-email:
    description: "Regular expression to check commit author email"
    required: false
    default: ".*"
  re-commit-author-name:
    description: "Regular expression to check commit author name"
    required: false
    default: |
      ^[A-Z][a-z]+[A-Za-z]*(-[A-Z][a-z]+[A-Za-z]*)*( ((St\.|[Vv]an|[Dd]e[lr]?|[Ll]a)|[A-Z](\.|[a-z]+[A-Za-z]*)(-[A-Z](\.|[a-z]+[A-Za-z]*))*))*( [A-Z][a-z]+[A-Za-z]*(-[A-Z][a-z]+[A-Za-z]*)*)$
  re-commit-committer-email:
    description: "Regular expression to check commit author email"
    required: false
    default: ".*"
  re-commit-committer-name:
    description: "Regular expression to check commit author name"
    required: false
    default: |
      ^[A-Z][a-z]+[A-Za-z]*(-[A-Z][a-z]+[A-Za-z]*)*( ((St\.|[Vv]an|[Dd]e[lr]?|[Ll]a)|[A-Z](\.|[a-z]+[A-Za-z]*)(-[A-Z](\.|[a-z]+[A-Za-z]*))*))*( [A-Z][a-z]+[A-Za-z]*(-[A-Z][a-z]+[A-Za-z]*)*)$
  re-commit-message-body:
    description: "Regular expression to check commit message body"
    required: false
    default: ".*"
  re-commit-message-split:
    description: "Regular expression to split commit message into subject and body"
    required: false
    default: "([^\n]*)(?:\n\n(.*))?"
  re-commit-message-subject:
    description: "Regular expression to check commit message subject"
    required: false
    default: |
      ^(([A-Z]{2,10}-[0-9]+)(, [A-Z]{2,10}-[0-9]+)*: )?\b(?!Made)(?![A-Za-z]*(ing|ung|ang|ed|id|[^s]s)\b)[A-Z][a-z]*\b [/\- ._,()A-Za-z0-9]*[)A-Za-z0-9]$
  re-pull-request-title:
    description: "Regular expression to check pull request title"
    required: false
    default: |
      ^([A-Z]{2,10}-[0-9]+)(, [A-Z]{2,10}-[0-9]+)*: \b(?!Made)(?![A-Za-z]*(ing|ung|ang|ed|id|[^s]s)\b)[A-Z][a-z]*\b [/\- ._,()A-Za-z0-9]*[)A-Za-z0-9]$
runs:
  using: "node12"
  main: "index.js"
