name: "gitlint-action-2024"
description: "Check if naming conventions for commits, branches, and pull requests are respected"
branding:
  icon: "check"
  color: "blue"
inputs:
  commit-message-body-max-length:
    description: "Max. length of commit message body"
    required: false
    default: 72
  commit-message-body-min-length:
    description: "Min. length of commit message body"
    required: false
    default: -1
  commit-message-subject-max-length:
    description: "Max. length of commit message subject"
    required: false
    default: 50
  commit-message-subject-min-length:
    description: "Min. length of commit message subject"
    required: false
    default: -1
  github-token:
    description: "GitHub token used to access api"
    required: true
    default: ${{ github.token }}
  prohibit-blank-lines-cm-body:
    description: "Prohibit blank lines in commit message body"
    required: false
    default: false
  prohibit-unknown-commit-authors:
    description: "Prohibit commit authors that are not known to GitHub"
    required: false
    default: true
  prohibit-unknown-commit-committers:
    description: "Prohibit commit committers that are not known to GitHub"
    required: false
    default: true
  prohibit-unsigned-commits:
    description: "Prohibit commits without a valid signature"
    required: false
    default: false
  re-branch-name:
    description: "Regular expression to check branch name"
    required: false
    default: ".*"
  re-commit-author-email:
    description: "Regular expression to check commit author email"
    required: false
    default: ".*"
  re-commit-author-name:
    description: "Regular expression to check commit author name"
    required: false
    default: ".*"
  re-commit-committer-email:
    description: "Regular expression to check commit author email"
    required: false
    default: ".*"
  re-commit-committer-name:
    description: "Regular expression to check commit author name"
    required: false
    default: ".*"
  re-commit-message-body:
    description: "Regular expression to check commit message body"
    required: false
    default: ".*"
  re-commit-message-split:
    description: "Regular expression to split commit message into subject and body"
    required: false
    default: "([^\n]*)(?:\n\n(.*))?"
  re-commit-message-subject:
    description: "Regular expression to check commit message subject"
    required: false
    default: "^[A-Z].*((?!\\.).)$"
  re-pull-request-title:
    description: "Regular expression to check pull request title"
    required: false
    default: "^[A-Z].*((?!\\.).)$"
  re-tag-name:
    description: "Regular expression to check tag name"
    required: false
    default: ".*"
runs:
  using: "node20"
  main: "index.js"
